### ISSUE TITLE
Deprecated 'lit-element' module warning

### ISSUE THREAD

**Issue by nicholaslimgovtech** [GovTechSG/sgds-web-component#170]
### Prerequisites

- [X] I have [searched](https://github.com/GovTechSG/sgds-web-component/issues) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/GovTechSG/sgds-web-component/blob/master/CONTRIBUTING.md)

### Describe the issue

Hello team, recently have been noticing the following warning appearing in the browser console when using the web-components.

`The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.`

This can also be observed when running the unit tests.
Using Lit v3 should be able to clear the warning (have tried upgrading on my local and ran unit test without issue), so this may be something you want to consider.

Thanks!

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### Describe your frontend stack. What version of React and @govtechsg/sgds-web-component are you using? CSR or SSR?

React v18.2, sgds-web-component v1.0.2

**Comment by clukhei** [comment]
Hi @nicholaslimgovtech, the underlying reason for console warning lies with one of the postprocessing plugin which uses `lit-element` by default. Fortunately, the newer version of that package now uses `lit` rather than `lit-element`. 

have created the fix, will link it here soon

**Comment by clukhei** [comment]
You can test out the fixes in released in`[ v1.1.0-rc.0](https://www.npmjs.com/package/@govtechsg/sgds-web-component/v/1.1.0-rc.0)` 

will release to stable once i finish other testings

**Comment by nicholaslimgovtech** [comment]
Thanks @clukhei for looking into this!
Can confirm that I no longer see the warnings with the new update :)

**Comment by clukhei** [comment]
thanks @nicholaslimgovtech. 

Promoted to stable release v1.1.0  https://github.com/GovTechSG/sgds-web-component/releases/tag/v1.1.0
