### ISSUE TITLE
Support drawer web component header styling

### ISSUE THREAD

**Issue by lixinW** [GovTechSG/sgds-web-component#225]
### Prerequisites

- [X] I have [searched](https://github.com/GovTechSG/sgds-web-component/issues) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/GovTechSG/sgds-web-component/blob/master/CONTRIBUTING.md)

### Proposal

Currently the header only supports H2. Could we allow further customisation to style the header?

### Motivation and context

![image](https://github.com/user-attachments/assets/da4fed2f-8418-4b33-9489-8a3cc291b85f)

**Comment by tonghauhive** [comment]
There is a slot called `label` to allow further customisation on the header, so you can pass in the html elements and style it instead of adding the label through the `label` prop.


```
<sgds-drawer class="drawer-overview">
   <div slot="label" class="sub-title">
      <p>Filters within</p>
      <h5>Product information</h5>
   </div>
   Lorem ipsum dolor sit amet, consectetur adipiscing elit.
   <sgds-button slot="footer" variant="primary">Close</sgds-button>
</sgds-drawer>
```

**Comment by clukhei** [comment]
closing this issue as complete @lixinW
