### ISSUE TITLE
Main Nav Styling Options

### ISSUE THREAD

**Issue by yanbutan** [GovTechSG/sgds-web-component#55]
Hi I was trying out sgds-web-component main nav and wanted to customise style. Specifically to increase the side padding and change the background colour. There were no props i could pass in to customise this so i used a wrapper div instead, but this caused the CSS to break. Specifically the dropdown location gets shifted:

![Screenshot 2023-05-11 at 1 47 42 PM](https://github.com/GovTechSG/sgds-web-component/assets/44741317/a9955394-0492-441b-9b8b-be945736a8d5)

Was wondering if there will be a way to style components in the future?

Lit has this https://lit.dev/docs/components/styles/#customprops, which allows components to get styled from the outside.

**Comment by rav3** [comment]
Hey @yanbutan
Thanks for the feedback. We are going to expose the css custom variables for main nav in the next release.

**Comment by yanbutan** [comment]
Nicee

**Comment by rav3** [comment]
@yanbutan 
closing this issue as features are added in #54

**Comment by yanbutan** [comment]
okay thank you!
