### ISSUE TITLE
Diff breakpoints between mainnav and masthead

### ISSUE THREAD

**Issue by yanbutan** [GovTechSG/sgds-web-component#74]
Hi guys,

Breakpoint change difference between mainnav and masthead.

For masthead, it breaks at 1024px and stay the same throughout.

Desktop view:
![Screenshot 2023-05-26 at 4 01 52 PM](https://github.com/GovTechSG/sgds-web-component/assets/44741317/b6c5beaa-c473-4e25-9a6d-ed4e3eccd78e)

Mobile view:
![Screenshot 2023-05-26 at 4 02 15 PM](https://github.com/GovTechSG/sgds-web-component/assets/44741317/47fb3734-c9a9-4941-88c3-1a2082d73911)

However for mainnav, it seems like there's 3 breakpoints which makes it difficult for it to be in sync with the masthead's and vice versa. Video below:

https://github.com/GovTechSG/sgds-web-component/assets/44741317/8f55cecd-e3b1-4069-bfda-db3dc1128b37

Was wondering if there's a way to make these 2 components' breakpoint be synced?

Could I also confirm if you guys are using the [default bootstrap breakpoints](https://getbootstrap.com/docs/5.0/layout/breakpoints/)?

![Screenshot 2023-05-29 at 10 30 13 AM](https://github.com/GovTechSG/sgds-web-component/assets/44741317/8ddd46b4-c725-45f9-81fd-39e59cecd5be)

**Comment by rav3** [comment]
Hey @yanbutan 
Thanks for spotting this bug and we are looking into it 👍

**Comment by yanbutan** [comment]
Alrite, thank you!!

**Comment by clukhei** [comment]
Closing this as Masthead only need 2 breakpoint. >1024px [Desktop to tablet] and  <960px [mobile]
